name: network_request_backend
description: A server app that has mock APIs for testing network_request package using the shelf package.
version: 0.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  mime: ^1.0.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
